### ISSUE TITLE
Users can label questions with preset categories

### ISSUE THREAD

**Issue by CronaTronic** [Lior-za/Soen341UC3#13]
**Description**: As a user, I want to be able to associated my questions with a set of preset categories. Each category will have its own page where questions from a given category are displayed. 

**Story Points**: 5

**Tasks**:
- [ ] Add
- [ ] GUI combobox under a question box.
- [ ]  Populate the combobox from the database
- [ ]  When submitting the question the categories should be associated with it and saved under the question box.
- [ ]  Create a column in the database for the categories and make sure it has a reference to associated question. (Maybe the ID of the questions)
- [ ]  Test

**Comment by I-Dream-Of-Machines** [comment]
Added a user story label

**Comment by CronaTronic** [comment]
Not a core issue, moving to sprint 3

**Comment by Lior-za** [comment]
Tasks: 

- [ ] Add textbook under a question box.
- [ ] Make sure the textbook does live verification of existing tags in the database.
- [ ] When submitting the question the tags should be associated with it and saved under the question box.
- [ ] Create a column in the database for the tags and make sure it has a reference to associated question. (Maybe the ID of the questions)
- [ ] Test

**Comment by I-Dream-Of-Machines** [comment]
Based on discussions we split categories and tags. Tags are user defined while categories are preset, thus this feature will allow users to select a category for their question, not create categories.

**Comment by I-Dream-Of-Machines** [comment]
Closed it accidentally. @Lior-za, I moved your task list into the main description
