### ISSUE TITLE
Users can post a question

### ISSUE THREAD

**Issue by I-Dream-Of-Machines** [Lior-za/Soen341UC3#16]
Story Points: 3
Associated Tasks:

- [ ] UI for Post A Question button
- [ ] Redirect to a page with a form (for question submission)
- [ ] UI for question submission form
- [ ] Checks to ensure form has sufficient information to be submitted
- [ ] DML action to store form entry into DB
- [ ] Query to extract pertinent information and display on relevant Question category page

**Comment by I-Dream-Of-Machines** [comment]
To ensure the only logged in users can post a questions, should we make the Post A question button invisible to individuals that have not logged in or should we have a redirect to a login/register page.

**Comment by I-Dream-Of-Machines** [comment]
I like the idea of breaking down into to two, perhaps we can create an epic that has distinct user stories associated with it. I am going to add the extra user story in and then tag pertinent user stories with the epic tag.

**Comment by Lior-za** [comment]
I agree with both of you, I also think if a non logged in user clicks on submit a question it will redirect him to a user creation page.

**Comment by I-Dream-Of-Machines** [comment]
Completed by @CronaTronic
