### ISSUE TITLE
Users can post an answer to a question

### ISSUE THREAD

**Issue by I-Dream-Of-Machines** [Lior-za/Soen341UC3#17]
Associated Tasks:

- [x] UI for Answer Question button
- [x] Redirect to a page with a form (for answer submission)
- [x] UI for answer submission form
- [x] Checks to ensure form has sufficient information to be submitted
- [x] DML action to store form entry into DB
- [ ] Query to extract pertinent information and display on relevant Question page

**Comment by I-Dream-Of-Machines** [comment]
In this user story, the user will only be able to submit an answer to the question. For other user stories we may want to use nesting to allow users to interact with those who have submitted answers (i.e. we may want nesting of responses). If we are agreed on this, I will add another user story for this feature and we can resolve this on the next sprint.

**Comment by CronaTronic** [comment]
I like this idea. We could call them "Discussion" posts. I think both Question posts and Answer posts should have Discussion posts enabled.

**Comment by I-Dream-Of-Machines** [comment]
Agreed. I am going to add a user story that deals with this and include it an answer epic.

**Comment by Lior-za** [comment]
Sounds like a good idea, but why won't we just allow tagging of other user so they receive a notification once someone posts and answer and "tags" them. I think it would be easier to implement and keep the page look clean and easy to read.

**Comment by CronaTronic** [comment]
Hmm... notifying users is actually a good idea that we overlooked, but that wasn't the point of having Discussion posts. The idea is that users should be able to discuss a Question or Answer, like ask for more details about the Question or provide feedback on why an Answer isn't acceptable

**Comment by CronaTronic** [comment]
Here's a very rough idea of what I mean
![discussion hierarchy](https://user-images.githubusercontent.com/5100923/35478894-761dc2b4-03b7-11e8-91ea-ad434ad97fac.png)

**Comment by Lior-za** [comment]
Okay I understand now,  but wouldn't the site be to messy if we going to follow that layout/concept. I figured that all the comments towards an answer would be a discussion, until one of them is picked as an answer. This is just how i visualized it, but i am very open to the idea you have in mind.
![demo](https://user-images.githubusercontent.com/23342263/35523524-0b546992-04ed-11e8-8cc3-7f1af98f00ad.png)

**Comment by I-Dream-Of-Machines** [comment]
I do think though that discussion is distinct from an answer. I have here a screen shot from stack overflow to illustrate. 
<img width="779" alt="screen shot 2018-01-29 at 12 13 17 pm" src="https://user-images.githubusercontent.com/16230030/35523929-fbba31c8-04ed-11e8-8d0d-94b505deaf43.png">

**Comment by Lior-za** [comment]
Okay got it, thank you for clarifying it.

**Comment by I-Dream-Of-Machines** [comment]
Complete by @CronaTronic
