### ISSUE TITLE
Users can log in and log out of their accounts

### ISSUE THREAD

**Issue by I-Dream-Of-Machines** [Lior-za/Soen341UC3#26]
**Description:**

The user should be able to log in and out of the website in order to provide custom functionality. This includes things like preventing anonymous users from voting, preventing non-authors from accepting answers, etc.

**Tasks:**

- [x] Research how best to encrypt login info in django
- [x] Link to login in main header
- [x] Login webpage with email/password failure
- [x] Login failure notification
- [x] Logout button logs out and redirects to home page
- [x] Create account placeholder link for issue #4 
- [x] Forgot login info placeholder link for issue #18 
- [x] Test component functionality
- [x] Integrate
- [x] Test system functionality
